###############################
### Ketan Vithal Patel      ###
### June 16, 2021           ###
### Cybersecurity Boot Camp ###
###############################

## metricbeat-playbook.yml File:


---
- name: Installing and Launching Metricbeat
  hosts: webservers
  become: true
  tasks:

  # Use command module
  - name: Download Metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.7.1-amd64.deb

  # Use command module
  - name: Install Metricbeat deb
    command: dpkg -i metricbeat-7.7.1-amd64.deb

  # Use copy module
  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/roles/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  # Use command module
  - name: enable and configure system module
    command: metricbeat modules enable system

  # Use command module
  - name: setup metricbeat
    command: metricbeat setup

  # Use command module
  - name: start metricbeat service
    command: service metricbeat start
